### ISSUE TITLE
zstld and window issues

### ISSUE THREAD

**Issue by harikmenon** [HaliteChallenge/Halite-II#64]
I'm using Windows and I cannot get zstd installed from HaliteClient setup, nor from Facebook's github, and the Windows zstd executable won't even open the replay files because it does not recognize the suffix. Not entirely sure what the issue is since the replays downloaded from the Halite site can be opened without an issue.

https://forums.halite.io/t/what-is-the-encoding-for-hlt-files-generated-by-halite-downloadable-environment/177/2

**Comment by potatoes-are-salty** [comment]
Thanks for posting this harikmenon.  The specific error messages I get are as follows.  From a google search, this seems to be an issue compiling on Windows with Visual Studio, and it does not look like there is a simple solution.

```
zstd/lib/compress/zstd_compress.c(22) : fatal error C1083: Cannot open include file: 'string.h': No such file or directory
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\bin\\cl.exe' failed with exit status 2
```

**Comment by Snaar** [comment]
Do you have access to a newer version of msvc? We test build on 14.0 and 15.0 and it works fine there. If not we can try to figure something out.

**Comment by Snaar** [comment]
When you say you cannot get zstd installed from HaliteClient setup, what exactly are the commands that you run?

**Comment by potatoes-are-salty** [comment]
I am downloading a copy of msvc 15 from school now, hopefully that will work.

I just ran "python setup.py install", as well as "build" and "develop" substituted for install.  Manually downloading the zstd-1.3.1 and running the same commands did not work either, nor did downloading the zstd.exe executable and directly using that on the replay files (not a regular file).

**Comment by potatoes-are-salty** [comment]
Installing MSVC 15.0 Professional fixes the zstd installation issue for me, and now I can get the Halite Client installed and working.  I was using MSVC 12.0 before, so I guess it must not work for older versions.

**Comment by Snaar** [comment]
👍
